# Generated by Django 2.2.5 on 2019-09-26 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190926_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='accepted_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
