# Generated by Django 2.2.5 on 2019-09-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190927_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryimage',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_images', to='api.Question'),
        ),
    ]
