# Generated by Django 2.2.5 on 2019-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190927_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='is_a_match',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
