# Generated by Django 2.2.5 on 2019-09-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190927_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
