# Generated by Django 2.2.5 on 2019-09-26 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20190927_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='primaryimage',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='primary_images_answered', to=settings.AUTH_USER_MODEL),
        ),
    ]
