# Generated by Django 2.2.5 on 2019-09-27 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20190927_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_by', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='secondaryimage',
            old_name='related_image',
            new_name='primary_image',
        ),
        migrations.RemoveField(
            model_name='primaryimage',
            name='question',
        ),
        migrations.AlterField(
            model_name='primaryimage',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='questions_answered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='primaryimage',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_images', to='api.Task'),
        ),
    ]
